name: D2L-Toaster
on: pull_request
jobs:

  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
  sauce:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: SauceLabs Tests
        run: npm run test:sauce
        env:
          SAUCE_USERNAME: Desire2Learn
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
